name: Report domain(s)
description: Please use this template to report domains so they can be properly incorporated with the workflows.
body:
  - type: textarea
    attributes:
      label: What domain(s) should be blocked?
      placeholder: |
        example.com
        https://www.example.com
        http://example.com/index.php
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should they be blocked?
      placeholder: |
        Phishing domains reported here https://example.com/.
        Delivery scam. See https://example.com/.
        URL in phishing SMS.
    validations:
      required: true