name: Manually add domains
run-name: Manuall add domains
on:
  issues:
    types:
      - labeled

jobs:
  read_domains:
    if: github.event.label.name == 'add domain'
    steps:
      - name: Read issue content
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })