name: Add subdomains
run-name: Add subdomains
on:
  workflow_dispatch:
  schedule:
    # Daily at 4am (GMT+8)
    - cron: '0 20 * * *'

jobs:
  add-subdomains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: add_subdomains.sh
        run: bash "workflow_scripts/add_subdomains.sh"

      - name: Commit and push
        run: |
          git config user.email '${{ vars.GIT_EMAIL }}'
          git config user.name '${{ vars.GIT_USERNAME }}'
          git add "${{ vars.RAW_FILE }}"
          git diff-index --quiet HEAD || git commit -m "Add subdomains"
          git push
