name: Add subdomains
run-name: Add subdomains
on:
  schedule:
    # Daily at 3:30am (GMT+8)
    - cron: "30 19 * * *"
  workflow_dispatch:
jobs:
  Add-subdomains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run add_subdomains.sh
        run: bash "workflow_scripts/add_subdomains.sh"
      - name: Commit and push changes
        env:
          COMMIT_MESSAGE: 'Add subdomains'
        run: |
          git config user.email "${{secrets.GIT_EMAIL}}"
          git config user.name "${{vars.GIT_USERNAME}}"
          git add "${{vars.RAW_FILE}}"
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
          git push
