name: Add header to raw file
run-name: Add header to raw file
on:
  push:
    paths:
      - "raw.txt"
jobs:
  Add-header-to-raw-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run add_raw_header.sh
        run: bash "workflow_scripts/add_raw_header.sh"
