name: Retrieve domains
run-name: Retrieve domains
on:
  schedule:
    # Daily at 3am (GMT+8)
    - cron: "0 19 * * *"
jobs:
  Retrieve-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run auto_retrieve.sh
        run: bash "workflow_scripts/auto_retrieve.sh"
