name: Retrieve domains
run-name: Retrieve domains
on:
  schedule:
    # Daily at 5am (GMT+8)
    - cron: "0 21 * * *"
jobs:
  Retrieve-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run retrieve.sh
        run: bash "retrieve.sh" u
