name: Retrieve domains
run-name: Retrieve domains
on:
  workflow_dispatch:
  schedule:
    # Daily at 5.05am (GMT+8)
    - cron: '5 21 * * *'

jobs:
  retrieve-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: retrieve.sh
        run: bash retrieve.sh u
