name: Retrieve domains
run-name: Retrieve domains
on:
  schedule:
    # Daily at 4:20am (GMT+8)
    - cron: "20 20 * * *"
  workflow_dispatch:
jobs:
  Retrieve-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run retrieve.sh
        run: bash "retrieve.sh" u
