name: Automated retrieval
run-name: Automated retrieval
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
permissions:
  contents: write

jobs:
  # This condition lets the job run even if any of the previous jobs failed
  # ${{ ! cancelled() }}

  # This condition prevents the job from running if the test job failed
  # ${{ needs.test-functions.result == 'success' }}

  test-functions:
    uses: ./.github/workflows/test_functions.yml

  tidy-repo:
    needs: test-functions
    if: ${{ ! cancelled() }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prune wildcards file
        run: |
          while read -r wildcard; do
            if (( $(grep -c "$wildcard" data/raw.txt) >= 10 )); then
              printf "%s\n" "$wildcard"
            fi
          done < config/wildcards.txt > temp
          mv temp config/wildcards.txt

      - name: Prune logs
        run: |
          # 250,000 is enough for a month's worth of logs.
          bash scripts/tools.sh --prune-lines config/domain_log.csv 250000
          bash scripts/tools.sh --prune-lines config/source_log.csv 10000

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: tidy repo"
          git push -q

  build-nsfw:
    needs: [test-functions, tidy-repo]
    if: ${{ ! cancelled() }}
    uses: ./.github/workflows/build_nsfw.yml

  retrieve-domains:
    needs: [test-functions, build-nsfw]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/retrieve_domains.yml
    secrets: inherit

  check-dead:
    needs: [test-functions, retrieve-domains]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/check_dead.yml

  check-unparked:
    needs: [test-functions, check-dead]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/check_unparked.yml

  # Run validation after dead/unparked checks to process subdomains
  validate:
    needs: [test-functions, check-unparked]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/validate_domains.yml
    secrets: inherit

  build:
    needs: [test-functions, validate]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/build_lists.yml

  update-readme:
    needs: build
    # Run only if build was successful
    if: ${{ ! cancelled() && needs.build.result == 'success' }}
    uses: ./.github/workflows/update_readme.yml
