name: Build
run-name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - "data/raw.txt"
  schedule:
    # Daily at 1am (GMT+8)
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Provide Git identity
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}

      - name: build.sh
        run: bash build.sh
