name: Build blocklist
run-name: Build blocklist
on:
  push:
    paths:
      - "data/raw.txt"
jobs:
  Build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Domains list
        run: bash "workflow_scripts/build_domains.sh"
      - name: Build Adblock Plus list
        run: bash "workflow_scripts/build_adblock.sh"
      - name: Update domains/entries count
        run: bash "workflow_scripts/update_count.sh"
      - name: Push changes
        run: bash "workflow_scripts/push_changes.sh"
