name: Build blocklist
run-name: Build blocklist
on:
  push:
    paths:
      - "data/raw.txt"
  schedule:
    # Daily at 5am (GMT+8)
    - cron: "0 21 * * *"
jobs:
  Build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Domains list
        run: bash "workflow_scripts/build_domains.sh"
      - name: Build Adblock Plus list
        run: bash "workflow_scripts/build_adblock.sh"
      - name: Save changes
        run: bash "workflow_scripts/save_changes.sh"
