name: Build lists
run-name: Build lists
on:
  workflow_dispatch:
  push:
    paths:
      - "data/raw.txt"
  schedule:
    # Daily at 4:50am (GMT+8)
    - cron: "50 20 * * *"

jobs:
  build-lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Domains list
        run: bash "workflow_scripts/build_domains.sh"

      - name: Build Adblock Plus list
        run: bash "workflow_scripts/build_adblock.sh"

      - name: Save changes
        run: bash "workflow_scripts/save_changes.sh"
