name: Check scripts
run-name: Check scripts
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: legacy