name: Check for parked domains
run-name: Check for parked domains
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  workflow_call:
permissions:
  contents: write

jobs:
  check-parked-part-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: check_parked.sh part 1
        run: bash scripts/check_parked.sh part1

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: check for parked domains (1)"
          git push -q

  check-parked-part-2:
    needs: check-parked-part-1
    if: ${{ ! cancelled() }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: check_parked.sh part 2
        run: bash scripts/check_parked.sh part2

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: check for parked domains (2)"
          git push -q

  remove-parked-domains:
    needs: check-parked-part-2
    if: ${{ ! cancelled() }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: check_parked.sh remove
        run: bash scripts/check_parked.sh remove

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: remove parked domains"
          git push -q
