name: Valid entries check
run-name: Valid entries check
on:
  schedule:
    # Daily at 5am (GMT+8)
    - cron: "0 21 * * *"
jobs:
  Valid-entries-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run check.sh
        run: bash "workflow_scripts/check.sh"
