name: ShellCheck
run-name: ShellCheck
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'

jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: legacy