name: Valid entries check
run-name: Valid entries check
on:
  workflow_dispatch:
  schedule:
    # Daily at 4am (GMT+8)
    - cron: '0 20 * * *'

jobs:
  Valid-entries-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Empty line check
        run: |
          if grep -q '^[[:space:]]*$' "${{ vars.RAW_FILE }}"; then
            echo -e "\nEmpty lines found. Removing..."           

            awk NF "${{ vars.RAW_FILE }}" > raw.tmp
            mv raw.tmp "${{ vars.RAW_FILE }}"

            echo
            exit 1
          fi

      - name: Case check
        if: success() || failure()
        run: |
          > check.tmp
          grep '[A-Z]' "${{ vars.RAW_FILE }}" > check.tmp || true

          if [[ -s check.tmp ]]; then
            echo -e "\nEntries with capitalized letters found:"
            cat check.tmp

            tr '[:upper:]' '[:lower:]' < "${{ vars.RAW_FILE }}" > raw.tmp
            mv raw.tmp "${{ vars.RAW_FILE }}"

            echo
            exit 1
          fi

      - name: Duplicate check
        if: success() || failure()
        run: |
          > check.tmp
          sort "${{ vars.RAW_FILE }}" | uniq -d > check.tmp

          if [[ -s check.tmp ]]; then
            echo -e "\nDuplicates found:"
            cat check.tmp

            sort -u "${{ vars.RAW_FILE }}" -o "${{ vars.RAW_FILE }}"

            echo
            exit 1
          fi

      - name: Whitelisted TLDs check
        if: success() || failure()
        run: |
          > check.tmp
          grep -E '\.(gov|edu)(\.[a-z]{2})?$' "${{ vars.RAW_FILE }}" > check.tmp || true

          if [[ -s check.tmp ]]; then
            echo -e "\nDomains with whitelisted TLDs found:"
            cat check.tmp

            comm -23 "${{ vars.RAW_FILE }}" check.tmp > raw.tmp
            mv raw.tmp "${{ vars.RAW_FILE }}"

            echo
            exit 1
          fi

      - name: Invalid domains check
        if: success() || failure()
        run: |
          > check.tmp
          grep -vE '^[[:alnum:].-]+\.[[:alnum:]-]{2,}$' "${{ vars.RAW_FILE }}" > check.tmp || true
         
          if [[ -s check.tmp ]]; then
            echo -e "\nInvalid domains found:"
            cat check.tmp

            comm -23 "${{ vars.RAW_FILE }}" check.tmp > raw.tmp
            mv raw.tmp "${{ vars.RAW_FILE }}"

            echo
            exit 1
          fi

      - name: Commit and push
        if: failure()
        run: |
          COMMIT_MSG='Remove invalid entries'
          FILES_TO_ADD=( "${{ vars.RAW_FILE }}" )
          git config user.email '${{ vars.GIT_EMAIL }}'
          git config user.name '${{ vars.GIT_USERNAME }}'
          git add "${FILES_TO_ADD[@]}"
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MSG"
          git push
