name: Valid entries check
run-name: Valid entries check
on:
  schedule:
    # Daily at 4am (GMT+8)
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  Valid-entries-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run check_raw.sh
        run: bash "workflow_scripts/check_raw.sh"
      - name: Commit and push changes
        env:
          raw_file="data/raw.txt"
          commit_message='Remove invalid entries'
        run: |
          git config user.email ${{secrets.git_email}}
          git config user.name ${{env.git_username}}
          #git add "$raw_file"
          #git commit -m "$commit_message"
          #git push
