name: Check lists
run-name: Check lists
on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'

jobs:
  check-lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: check.sh
        run: bash check.sh

      - name: Push
        if: always()
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git diff-index --quiet HEAD || git commit -am "Check lists"
          git push -q
