name: Check script
run-name: Check script
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'

jobs:
  check-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: legacy