name: Check for unparked domains
run-name: Check for unparked domains
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write

jobs:
  check-unparked-domains:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: check_parked.sh
        run: bash scripts/check_parked.sh checkunparked

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: check for unparked domains"
          git push -q
