name: Valid entries check
run-name: Valid entries check
on:
  schedule:
    # Daily at 4am (GMT+8)
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  Valid-entries-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run check_raw.sh
        run: bash "workflow_scripts/check_raw.sh"
      - name: Commit and push changes
        if: success() || failure()
        run: |
          COMMIT_MSG="Remove invalid entries"
          FILES_TO_ADD=( "${{vars.RAW_FILE}}" )
          git config user.email "${{secrets.GIT_EMAIL}}"
          git config user.name "${{vars.GIT_USERNAME}}"
          git add "${FILES_TO_ADD[@]}"
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MSG"
          git push
