name: Valid entries check
run-name: Valid entries check
on:
  workflow_dispatch:
  schedule:
    # Daily at 4am (GMT+8)
    - cron: '0 20 * * *'

jobs:
  Valid-entries-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Empty line check
        run: |
          if grep -q '^[[:space:]]*$' "${{ vars.RAW_FILE }}"; then
            echo -e "\nEmpty lines found. Removing..."           
            awk NF "${{ vars.RAW_FILE }}" > 1.tmp
            exit 1
          fi

      - name: Case check
         if: success() || failure()
         run: |
           > check.tmp
           grep '[A-Z]' 1.tmp > check.tmp || true

           if [[ -s check.tmp ]]; then
             echo -e "\nEntries with capitalized letters found:"
             cat check.tmp
             tr '[:upper:]' '[:lower:]' < 1.tmp > 2.tmp
             exit 1
           fi

      - name: Duplicate check
         if: success() || failure()
         run: |
           > check.tmp
           sort 2.tmp | uniq -d > check.tmp

           if [[ -s check.tmp ]]; then
             echo -e "\nDuplicates found:"
             cat check.tmp
             sort -u 2.tmp -o 2.tmp
             exit 1
           fi

      - name: Whitelisted TLDs check
         if: success() || failure()
         run: |
           > check.tmp
           grep -E '\.(gov|edu)(\.[a-z]{2})?$' 2.tmp > check.tmp || true

           if [[ -s check.tmp ]]; then
             echo -e "\nDomains with whitelisted TLDs found:"
             cat check.tmp
             comm -23 2.tmp check.tmp > 3.tmp
           fi

      - name: Invalid domains check
         if: success() || failure()
         run: |
           > check.tmp
           grep -vE '^[[:alnum:].-]+\.[[:alnum:]-]{2,}$' 3.tmp > check.tmp || true
         
           if [[ -s check.tmp ]]; then
             echo -e "\nInvalid domains found:"
             cat check.tmp
             comm -23 3.tmp check.tmp > 4.tmp
           fi

      - name: Replace blocklist with filtered blocklist 
        if: failure()
        run: mv 4.tmp "${{ vars.RAW_FILE }}"

      - name: Commit and push
        if: failure()
        run: |
          COMMIT_MSG='Remove invalid entries'
          FILES_TO_ADD=( "${{ vars.RAW_FILE }}" )
          git config user.email '${{ vars.GIT_EMAIL }}'
          git config user.name '${{ vars.GIT_USERNAME }}'
          git add "${FILES_TO_ADD[@]}"
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MSG"
          git push
