name: Remove daed domains
run-name: Remove dead domains
on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 2am (GMT+8)
    - cron: '0 18 * * 0'

jobs:
  remove-dead-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provide Git identity
        run: |
          git config user.email '${{ vars.GIT_EMAIL }}'
          git config user.name '${{ vars.GIT_USERNAME }}'

      - name: dead.sh
        run: bash dead.sh