name: Remove dead domains
run-name: Scheduled dead domains removal
on:
  schedule:
    # Run daily
    - cron: "0 0 * * *"
jobs:
  Remove-dead-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dead.sh
        run: bash dead.sh
