name: End-to-end build
run-name: End-to-end build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  prep:
    uses: ./.github/workflows/toplist.yml

  retrieve:
    needs: [test, update-toplist]
    uses: ./.github/workflows/retrieve.yml
    env:
      google_search_id: ${{ secrets.SEARCH_ID }}
      google_search_id_2: ${{ secrets.SEARCH_ID2 }}
      google_search_api_key: ${{ secrets.SEARCH_API_KEY }}
      google_search_api_key_2: ${{ secrets.SEARCH_API_KEY2 }}
      aa419_api_id: ${{ secrets.AA419_API_ID }}

  dead-check:
    needs: retrieve
    uses: ./.github/workflows/dead.yml

  build:
    needs: dead-check
    uses: ./.github/workflows/build.yml

