name: Generate domains list
run-name: Generate domains list
on:
  push:
    paths:
      - "raw.txt"
jobs:
  Generate-domains-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run generate_domains.sh
        run: bash "workflow_scripts/generate_domains.sh"
