name: Update blocklist header and README count
run-name: Update domains count
on:
  push:
    paths:
      - "domains"
jobs:
  Update-domains-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run header.sh
        run: bash "workflow_scripts/header.sh"
