name: Daily maintenance
run-name: Daily maintenance
on:
  workflow_dispatch:
  schedule:
    # Daily at 12am (GMT+8)
    - cron: '0 16 * * *'

jobs:
  daily-maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: maintain.sh
        run: bash maintain.sh

      - name: Push
        if: always()
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "List maintenance"
          git push -q
