name: Remove dead domains
run-name: Remove dead domains
on:
  schedule:
    # Daily at 3am (GMT+8)
    - cron: "0 19 * * *"
  push:
    paths:
      - "legacy/test"
jobs:
  Remove-dead-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run remove_dead.sh
        run: bash "workflow_scripts/remove_dead.sh"
