name: Test workflow
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          GIT_EMAIL: ${{env.GIT_EMAIL}}
        run: echo "Email is $GIT_EMAIL"
