name: Test retrieval
run-name: Test retrieval
on:
  workflow_dispatch:
  push:
    paths:
      - 'retrieve.sh'

jobs:
  test-retrieval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test.sh
        run: bash test.sh