name: Run tests
run-name: Run tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Run ShellCheck
        run: bash test.sh 'shellcheck'

  test-retrieval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Test retrieve.sh
        run: bash test.sh 'retrieval'

  test-toplist-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Test toplist check
        run: bash test.sh 'toplist'

  test-lists-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Test check.sh
        run: bash test.sh 'check'

  test-dead:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          ref: main
      - name: Test dead.sh
        run: bash test.sh 'dead'
