name: Run tests
run-name: Run tests
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'
      - '**.yml'

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*legacy/.*
          VALIDATE_BASH_EXEC: false
          VALIDATE_CHECKOV: false
          VALIDATE_MARKDOWN: false
          VALIDATE_SHELL_SHFMT: false

  test-retrieval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test retrieve.sh
        run: bash test.sh retrieval

  test-lists-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test check.sh
        run: bash test.sh check

  test-dead:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test dead.sh
        run: bash test.sh dead