name: Run tests
run-name: Run tests
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: | 
          wget -qO - "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJ
          printf "%s\n" "$(shellcheck-stable/shellcheck --version)"
          error=false
          for script in *.sh */*.sh; do
              [[ "$script" == legacy/* ]] && continue
              scripts=$(printf "%s\n%s\n" "$scripts" "$script")
              shellcheck-stable/shellcheck "$script" || error=true
          done
          printf "\nScripts checked:%s\n" "$scripts"
          [[ "$error" == true ]] && exit 1 || exit 0

  test-retrieval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test retrieve.sh
        run: bash test.sh retrieval

  test-lists-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test check.sh
        run: bash test.sh check

  test-dead:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test dead.sh
        run: bash test.sh dead