name: Test
run-name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: |
          cd data
          npm i -g @adguard/dead-domains-linter
          dead-domains-linter -i raw.txt --show
