name: Test
run-name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: |
          npm install -D @adguard/aglint
          npx aglint init
          npx aglint data/raw.txt
