name: Test
run-name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "run1" > temp.txt
      - run: echo "run2" >> temp.txt
      - run: echo "run2" >> temp.txt
      - name: Push changes
        run: bash "workflow_scripts/test.sh"
