name: Test workflow
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Command 0
        env:
          MESSAGE: ${{vars.RAW_FILE}} ${{vars.TOPLIST_FILE}}
        run: echo "$MESSAGE"
      - name: Command 1
        run: |
          echo "Exiting with error..."
          exit 1
      - name: Command 2
        if: failure()
        run: echo "This should show"
