name: Update toplists
run-name: Update toplists
on:
  workflow_dispatch:
  schedule:
    # Daily at 4:10am (GMT+8)
    - cron: '10 20 * * *'

jobs:
  Update-toplists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download toplists
        run: |
          wget -q https://raw.githubusercontent.com/hagezi/dns-data-collection/main/top/toplist.txt -O "${{ vars.TOPLIST_FILE }}"
          sort -u "${{ vars.TOPLIST_FILE }}" -o "${{ vars.TOPLIST_FILE }}"

          wget -q https://raw.githubusercontent.com/hagezi/dns-data-collection/main/top/toplist-merged.txt -O "${{ vars.SUBDOMAINS_TOPLIST_FILE }}"
          sort -u "${{ vars.SUBDOMAINS_TOPLIST_FILE }}" -o "${{ vars.SUBDOMAINS_TOPLIST_FILE }}"

      - name: Commit and push 
        if: success() || failure()
        run: |
          COMMIT_MSG="Update toplists"
          FILES_TO_ADD=( "${{ vars.TOPLIST_FILE }}" "${{ vars.SUBDOMAINS_TOPLIST_FILE }}" )

          git config user.email "${{ vars.GIT_EMAIL }}"
          git config user.name "${{ vars.GIT_USERNAME }}"
          git add "${FILES_TO_ADD[@]}"
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MSG"
          git push

      - name: Blocklist check
        run: |
          comm -12 "${{ vars.RAW_FILE }}" "${{ vars.TOPLIST_FILE }}" | grep -vxFf "${{ vars.BLACKLIST_FILE }}" > in_toplist.tmp

          if [[ -s in_toplist.tmp ]]; then
            echo -e "\nDomains found in the toplist:"
            cat in_toplist.tmp
            echo
            exit 1
          else
            echo -e "\nNo domains found in the toplist.\n"
            exit 0
          fi


