name: Whitelist check
run-name: Whitelist check
on:
  workflow_dispatch:
  push:
    paths:
      - "whitelist.txt"

jobs:
  Whitelist_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Whitelist check
        run: |
          cat "${{ vars.WHITELIST_FILE }}"
