name: Whitelist check
run-name: Whitelist check
on:
  workflow_dispatch:
  push:
    paths:
      - "whitelist.txt"

jobs:
  Whitelist_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Whitelist check
        run: |
          grep -Ff "${{ vars.WHITELIST_FILE }}" "${{ vars.RAW_FILE }}" | grep -vxFf "${{ vars.BLACKLIST_FILE }}" > whitelisted.tmp
          cat whitelisted.tmp
